# permissions for end users to view machinenodepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinenodepool-viewer-role
rules:
- apiGroups:
  - imperator.imprator.io
  resources:
  - machinenodepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imperator.imprator.io
  resources:
  - machinenodepools/status
  verbs:
  - get
