# permissions for end users to view machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-viewer-role
rules:
- apiGroups:
  - imperator.imprator.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imperator.imprator.io
  resources:
  - machines/status
  verbs:
  - get
