name: builds
on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      -
        name: build test
        run: make build

  build-image:
    runs-on: ubuntu-20.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      -
        name: Build imperator image
        run: make docker-build
