name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Fetch
        run: git fetch --tags -f
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      -
        name: Build imperator-controller image
        run: make docker-build IMAGE_TAG_VERSION="${GITHUB_REF#refs/tags/}"
      -
        name: Release imperator-controller image
        run: make docker-release IMAGE_TAG_VERSION="${GITHUB_REF#refs/tags/}"
