name: unit tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: test
        run: make test
